In [1]:
import numpy as np

# Create a random vector of size 20 with float values in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

# Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)

# Find indices of max values along each row
row_max_indices = np.argmax(reshaped_array, axis=1)

# Use np.where to replace max values with 0
reshaped_array = np.where(
    np.arange(5) == row_max_indices[:, None],  # Create a boolean mask for max values
    0,  # Replace max values with 0
    reshaped_array  # Keep other values unchanged
)

print("Original random vector:")
print(random_vector)
print("\nReshaped array with max values replaced by 0:")
print(reshaped_array)


Original random vector:
[13.02225167 18.87065097 17.8354262  17.41499279  1.50230481  4.87139474
 12.19912795 16.60632551  5.9711424   1.70720274  4.52038826  4.46486723
  4.37223279 17.92375719  2.91726656 11.63081212 15.17005715  4.41907387
 14.44361918  8.95435151]

Reshaped array with max values replaced by 0:
[[13.02225167  0.         17.8354262  17.41499279  1.50230481]
 [ 4.87139474 12.19912795  0.          5.9711424   1.70720274]
 [ 4.52038826  4.46486723  4.37223279  0.          2.91726656]
 [11.63081212  0.          4.41907387 14.44361918  8.95435151]]
